config/routes.rb
Rails.application.routes.draw do
  root       'home#index'

  devise_for 'users'
  
  get        '/stacks',                 to: redirect("/")
  get        '/stacks/:slug',           to: 'stack#view',                    as: "stack"
  
  get        '/tools/:id',              to: 'tool#view',                     as: "tool"
  get        '/mystack',                to: 'my_stack#index',                as: "mystack"
  get        '/search',                 to: 'search#index',                  as: "search"
  get        '/about',                  to: 'pages#about',                   as: "about"

  get        '/mystack/languages/add',  to: 'programming_languages#new',     as: "new_language"
  post       '/mystack/languages/add',  to: 'programming_languages#create',  as: "add_language"
  
  get        '/mystack/languages/:id',  to: 'programming_languages#view',    as: "view_language"
  post        '/mystack/languages/:id', to: 'programming_languages#update',  as: "update_language"
  delete     '/mystack/languages/:id',  to: 'programming_languages#destroy', as: "delete_language"

  get        '/mystack/utilities/add',  to: 'utilities#new',                 as: "new_utility"
  post       '/mystack/utilities/add',  to: 'utilities#create',              as: "add_utility"
  
  get        '/mystack/utilities/:id',  to: 'utilities#view',                as: "view_utility"
  post       '/mystack/utilities/:id',  to: 'utilities#update',              as: "update_utility"
  delete     '/mystack/utilities/:id',  to: 'utilities#destroy',             as: "delete_utility"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_tool.rb
class BusinessTool < ApplicationRecord
  has_many :business_tools_users
  has_many :users, through: :business_tools_users
  
  validates_presence_of :name
end

app/models/business_tool_user.rb
class BusinessToolUser < ApplicationRecord
  belongs_to :business_tool
  belongs_to :user
end

app/models/business_tools_user.rb
class BusinessToolsUser < ApplicationRecord
  belongs_to :business_tool
  belongs_to :user
end

app/models/devop.rb
class Devop < ApplicationRecord
  has_many :devops_users
  has_many :users, through: :devops_users
  
  validates_presence_of :name
end

app/models/devop_user.rb
class DevopUser < ApplicationRecord
  belongs_to :devop
  belongs_to :user
end

app/models/devops_user.rb
class DevopsUser < ApplicationRecord
  belongs_to :devop
  belongs_to :user
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  has_many :programming_languages_users
  has_many :users, through: :programming_languages_users
  
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  devise                  :database_authenticatable,
                          :registerable,
                          :recoverable,
                          :rememberable,
                          :validatable
  
  before_save             :set_slug

  validates_presence_of   :name
  validates_uniqueness_of :name

  has_many :programming_languages_users
  has_many :programming_languages, through: :programming_languages_users
  
  has_many :users_utilities
  has_many :utilities,             through: :users_utilities
  
  has_many :business_tools_users
  has_many :business_tools,        through: :business_tools_users
  
  has_many :devops_users
  has_many :devops,                through: :devops_users

  private
    def set_slug
      self.slug = self.name.parameterize
    end
end

app/models/users_utility.rb
class UsersUtility < ApplicationRecord
  belongs_to :user
  belongs_to :utility

  validates :utility, uniqueness: { scope: :user }
end

app/models/utility.rb
class Utility < ApplicationRecord
  has_many :users_utilities
  has_many :users, through: :users_utilities
  
  validates_presence_of :name
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.order(:name).paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/tool_controller.rb
class ToolController < ApplicationController
  def view
    @tool = ProgrammingLanguage.find(params[:id])
    @users = @tool.users.order(:name).paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/utilities_controller.rb
class UtilitiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_utility, only: [:view, :update, :destroy]

  def view
  end

  def update
    @utility.details = utilities_params[:details]
    @utility.save
    redirect "Utility updated successfully!"
  end

  def new
    @utility = UsersUtility.new
  end

  def create
    @utility = UsersUtility.new(utilities_params)
    @utility.user = current_user

    if @utility.valid?
      @utility.save
      redirect "Utility added successfully!"
    else
      render "new"
    end
  end

  def destroy
    @utility.destroy
    redirect "Utility removed successfully!"
  end

  private

  def utilities_params
    params.require(:users_utility).permit(:utility_id, :details)
  end

  def set_utility
    @utility = UsersUtility.find_by!(user: current_user, utility_id: params[:id])
  end

  def redirect(message)
    redirect_to mystack_url, notice: message
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_stack_helper.rb
module MyStackHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/stack_helper.rb
module StackHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: "#", class: "gravatar img-circle")
      end
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/helpers/utilities_helper.rb
module UtilitiesHelper
end

app/views/utilities/_form.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3 well" style="border-radius: 0;">
    <%= form_for(users_utility, url: url, method: :post) do |f| %>
      <%= render "shared/error_messages", model: users_utility %>
      <% if url == new_utility_path %>
        <div class="field form-group">
          <%= f.label :utility_id %>
          <%= f.select :utility_id, Utility.all.collect {|u| [ u.name, u.id ] }, { include_blank: false}, {class: "form-control"} %>
        </div>
      <% end %>
      <div class="field form-group">
        <%= f.label :details %>
        <%= f.text_area :details, class: "form-control", placeholder: "For what you guys use this tool!" %>
      </div>
      <div class="field form-group">
        <% if url == new_utility_path %>
          <%= f.submit "Add Utility", class: "btn btn-primary" %>
        <% else %>
          <%= f.submit "Update #{users_utility.utility.name}", class: "btn btn-primary" %>
          <%= link_to "Remove #{users_utility.utility.name}", delete_utility_path(id: users_utility.utility), data: {confirm: "Are you sure?"}, method: :delete, class: "btn btn-danger" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/utilities/new.html.erb
<%= render "utilities/form", users_utility: @utility, url: add_utility_path %>

app/views/utilities/view.html.erb
<div class="jumbotron" style="text-align: center; border-radius: 0;">
  <h1>
    <%= @utility.utility.name %>
  </h1>
  <hr/>
  <% if !@utility.details.empty? %>
    <%= @utility.details %>
  <% else %>
    (No details)
  <% end %>
</div>
<%= render "utilities/form", users_utility: @utility, url: update_utility_path %>