config/routes.rb
Rails.application.routes.draw do
  root       'home#index'

  devise_for 'users'
  
  get        '/stacks',                 to: redirect("/")
  get        '/stacks/:slug',           to: 'stack#view',                    as: "stack"
  
  get        '/tools/:id',              to: 'tool#view',                     as: "tool"
  get        '/mystack',                to: 'my_stack#index',                as: "mystack"
  get        '/search',                 to: 'search#index',                  as: "search"
  get        '/about',                  to: 'pages#about',                   as: "about"

  get        '/mystack/languages/add',  to: 'programming_languages#new',     as: "new_language"
  post       '/mystack/languages/add',  to: 'programming_languages#create',  as: "add_language"
  
  get        '/mystack/languages/:id',  to: 'programming_languages#view',    as: "view_language"
  post        '/mystack/languages/:id', to: 'programming_languages#update',  as: "update_language"
  delete     '/mystack/languages/:id',  to: 'programming_languages#destroy', as: "delete_language"

  get        '/mystack/utilities/add',  to: 'utilities#new',                 as: "new_utility"
  post       '/mystack/utilities/add',  to: 'utilities#create',              as: "add_utility"
  
  get        '/mystack/utilities/:id',  to: 'utilities#view',                as: "view_utility"
  post       '/mystack/utilities/:id',  to: 'utilities#update',              as: "update_utility"
  delete     '/mystack/utilities/:id',  to: 'utilities#destroy',             as: "delete_utility"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_tool.rb
class BusinessTool < ApplicationRecord
  has_many :business_tools_users
  has_many :users, through: :business_tools_users
  
  validates_presence_of :name
end

app/models/business_tool_user.rb
class BusinessToolUser < ApplicationRecord
  belongs_to :business_tool
  belongs_to :user
end

app/models/business_tools_user.rb
class BusinessToolsUser < ApplicationRecord
  belongs_to :business_tool
  belongs_to :user
end

app/models/devop.rb
class Devop < ApplicationRecord
  has_many :devops_users
  has_many :users, through: :devops_users
  
  validates_presence_of :name
end

app/models/devop_user.rb
class DevopUser < ApplicationRecord
  belongs_to :devop
  belongs_to :user
end

app/models/devops_user.rb
class DevopsUser < ApplicationRecord
  belongs_to :devop
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise                  :database_authenticatable,
                          :registerable,
                          :recoverable,
                          :rememberable,
                          :validatable
  
  before_save             :set_slug

  validates_presence_of   :name
  validates_uniqueness_of :name

  has_many :programming_languages_users
  has_many :programming_languages, through: :programming_languages_users
  
  has_many :users_utilities
  has_many :utilities,             through: :users_utilities
  
  has_many :business_tools_users
  has_many :business_tools,        through: :business_tools_users
  
  has_many :devops_users
  has_many :devops,                through: :devops_users

  private
    def set_slug
      self.slug = self.name.parameterize
    end
end

app/models/users_utility.rb
class UsersUtility < ApplicationRecord
  belongs_to :user
  belongs_to :utility

  validates :utility, uniqueness: { scope: :user }
end

app/models/utility.rb
class Utility < ApplicationRecord
  has_many :users_utilities
  has_many :users, through: :users_utilities
  
  validates_presence_of :name
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.order(:name).paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/tool_controller.rb
class ToolController < ApplicationController
  def view
    @tool = ProgrammingLanguage.find(params[:id])
    @users = @tool.users.order(:name).paginate(:page => params[:page], :per_page => 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_stack_helper.rb
module MyStackHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/stack_helper.rb
module StackHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: "#", class: "gravatar img-circle")
      end
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/helpers/utilities_helper.rb
module UtilitiesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechStack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body class="container">
    <%= render "shared/navbar" %>
    <% if notice %>
      <div class="alert alert-info">
        <%= notice %>
      </div>
    <% end %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row" style="text-align: center;">
  <div class="col-md-8 col-md-offset-2">
    <h1>Why TechStack?</h1>
    <p>Why are companies beginning to share the specific mix of apps that's enabling their businesses to grow?
      Because they know it's the missing piece of the puzzle for developers, many of whom struggle to learn
      which tools certain companies use and why.</p>
    <h1>In fact, we want to quietly become a go-to platform for numerous players in the startup ecosystem for a few reasons.</h1>
    <p>The benefits are clearest for developers. "if you're trying to build a new on-demand service, you can come and see
      all the tools that Instacart uses." We also benefits companies; when big or small startups volunteer what tools they're
      using, they have a better shot at attracting developers who are well-versed in those very same technologies.</p>
  </div>
</div>

app/views/shared/_error_messages.erb
<% if model.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(model.errors.count, "error") %>.
    </div>
    <ul class="text-danger">
      <% model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.erb
<hr/>
<footer style="margin-bottom: 10px; text-align: right;">
  by <a href="https://www.github.com/dyotamo" target="_blank">@dyotamo</a> - <%= Time.now.year %>
</footer>

app/views/shared/_navbar.erb
<nav class="navbar navbar-default" style="border-radius: 0;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <strong>
        <%= link_to 'TS', root_path, class: "navbar-brand" %>
      </strong>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "About", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
            <%= if current_user then current_user.name else "Accounts" end %> <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <% if current_user %>
                <li><%= link_to 'My Stack', mystack_path %></li>
                <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
              <% else %>
                <li><%= link_to 'Log in', new_user_session_path %></li>
                <li><%= link_to 'Sign up', new_user_registration_path %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/shared/_search.erb
<%= form_for(:search, url: search_path, method: :get) do |f| %>
  <div class="input-group form-group">
    <%= f.text_field :text, placeholder: "Type the company name...", value: value, class: "form-control" %>
    <span class="input-group-btn">
      <%= f.submit 'Search', class: "btn btn-primary" %>
    </span>
  </div>
<% end %>