config/routes.rb
Rails.application.routes.draw do
  root       'home#index'

  devise_for 'users'
  
  get        '/stacks',                 to: redirect("/")
  get        '/stacks/:slug',           to: 'stack#view',                    as: "stack"
  
  get        '/tools/:id',              to: 'tool#view',                     as: "tool"
  get        '/mystack',                to: 'my_stack#index',                as: "mystack"
  get        '/search',                 to: 'search#index',                  as: "search"
  get        '/about',                  to: 'pages#about',                   as: "about"

  get        '/mystack/languages/add',  to: 'programming_languages#new',     as: "new_language"
  post       '/mystack/languages/add',  to: 'programming_languages#create',  as: "add_language"
  
  get        '/mystack/languages/:id',  to: 'programming_languages#view',    as: "view_language"
  post        '/mystack/languages/:id', to: 'programming_languages#update',  as: "update_language"
  delete     '/mystack/languages/:id',  to: 'programming_languages#destroy', as: "delete_language"

  get        '/mystack/utilities/add',  to: 'utilities#new',                 as: "new_utility"
  post       '/mystack/utilities/add',  to: 'utilities#create',              as: "add_utility"
  
  get        '/mystack/utilities/:id',  to: 'utilities#view',                as: "view_utility"
  post       '/mystack/utilities/:id',  to: 'utilities#update',              as: "update_utility"
  delete     '/mystack/utilities/:id',  to: 'utilities#destroy',             as: "delete_utility"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business_tool.rb
class BusinessTool < ApplicationRecord
  has_many :business_tools_users
  has_many :users, through: :business_tools_users
  
  validates_presence_of :name
end

app/models/business_tool_user.rb
class BusinessToolUser < ApplicationRecord
  belongs_to :business_tool
  belongs_to :user
end

app/models/business_tools_user.rb
class BusinessToolsUser < ApplicationRecord
  belongs_to :business_tool
  belongs_to :user
end

app/models/devop.rb
class Devop < ApplicationRecord
  has_many :devops_users
  has_many :users, through: :devops_users
  
  validates_presence_of :name
end

app/models/devop_user.rb
class DevopUser < ApplicationRecord
  belongs_to :devop
  belongs_to :user
end

app/models/devops_user.rb
class DevopsUser < ApplicationRecord
  belongs_to :devop
  belongs_to :user
end

app/models/programming_language.rb
class ProgrammingLanguage < ApplicationRecord
  has_many :programming_languages_users
  has_many :users, through: :programming_languages_users
  
  validates_presence_of :name
end

app/models/user.rb
class User < ApplicationRecord
  devise                  :database_authenticatable,
                          :registerable,
                          :recoverable,
                          :rememberable,
                          :validatable
  
  before_save             :set_slug

  validates_presence_of   :name
  validates_uniqueness_of :name

  has_many :programming_languages_users
  has_many :programming_languages, through: :programming_languages_users
  
  has_many :users_utilities
  has_many :utilities,             through: :users_utilities
  
  has_many :business_tools_users
  has_many :business_tools,        through: :business_tools_users
  
  has_many :devops_users
  has_many :devops,                through: :devops_users

  private
    def set_slug
      self.slug = self.name.parameterize
    end
end

app/models/users_utility.rb
class UsersUtility < ApplicationRecord
  belongs_to :user
  belongs_to :utility

  validates :utility, uniqueness: { scope: :user }
end

app/models/utility.rb
class Utility < ApplicationRecord
  has_many :users_utilities
  has_many :users, through: :users_utilities
  
  validates_presence_of :name
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.order(:name).paginate(:page => params[:page], :per_page => 10)
  end
end

app/controllers/my_stack_controller.rb
class MyStackController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/tool_controller.rb
class ToolController < ApplicationController
  def view
    @tool = ProgrammingLanguage.find(params[:id])
    @users = @tool.users.order(:name).paginate(:page => params[:page], :per_page => 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/my_stack_helper.rb
module MyStackHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/stack_helper.rb
module StackHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: "#", class: "gravatar img-circle")
      end
end

app/helpers/tool_helper.rb
module ToolHelper
end

app/helpers/utilities_helper.rb
module UtilitiesHelper
end

app/views/my_stack/index.html.erb
<h2>My Current Stack</h1>
<div class="row">
  <div class="col-md-3">
    <h4>Programming Languages <small>(<%= current_user.programming_languages.count %>)</small></h4>
    <ul>
      <% current_user.programming_languages.each do |tool| %>
        <li>
          <%= link_to tool.name, view_language_path(id: tool) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-3">
    <h4>Utilities <small>(<%= current_user.utilities.count %>)</small></h4>
    <ul>
      <% current_user.utilities.each do |tool| %>
        <li>
          <%= link_to tool.name, view_utility_path(id: tool) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-3">
    <h4>Devops <small>(<%= current_user.devops.count %>)</small></h4>
    <ul>
      <% current_user.devops.each do |tool| %>
        <li><%= tool.name %></li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-3">
    <h4>Business Tools <small>(<%= current_user.business_tools.count %>)</small></h4>
    <ul>
      <% current_user.business_tools.each do |tool| %>
        <li><%= tool.name %></li>
      <% end %>
    </ul>
  </div>
</div>
<hr/>
<div class="row">
  <div class="col-md-3">
    <%= link_to "Add Language", new_language_path, class: "btn btn-primary btn-xs" %>
  </div>
  <div class="col-md-3">
    <%= link_to "Add Utility", new_utility_path, class: "btn btn-primary btn-xs" %>
  </div>
  <div class="col-md-3">
  </div>
  <div class="col-md-3">
  </div>
</div>